TERM: screen-256color

font:
  size: 20.0
  normal:
    family: JetBrainsMonoMedium Nerd Font Mono
    style: Medium

  Bold:
    family: JetBrainsMonoMedium Nerd Font Mono
    style: Bold

  italic:
    family: JetBrainsMonoMedium Nerd Font Mono
    style: Italic

window:
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
  dimensions:
    columns: 0
    lines: 0

  decorations: none

  dynamic_title: true

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 1

  padding:
    x: 10
    y: 10

  dynamic_padding: true

startup_mode: windowed

key: return,
mods: Command,
action: SpawnNewInstance

cursor:
  style: Block

use_thin_strokes: true

live_config_reload: true

# BEGIN ACE
colors:
  primary:
    background: '#152733'
    foreground: '#dfd9d8'
  cursor:
    text:       '#24455b'
    cursor:     '#dfd9d8'
  normal:
    black:      '#24455b'
    red:        '#ff777a'
    green:      '#d97a9b'
    yellow:     '#ffba95'
    blue:       '#4684ae'
    magenta:    '#325f7d'
    cyan:       '#c7bcba'
    white:      '#dfd9d8'
  bright:
    black:      '#24455b'
    red:        '#ff777a'
    green:      '#d97a9b'
    yellow:     '#ffba95'
    blue:       '#4684ae'
    magenta:    '#325f7d'
    cyan:       '#c7bcba'
    white:      '#ded8d7'
# END ACE
