#!/usr/bin/env bash

# case $HOSTNAME in
#   kuro)  export LAN=eno1   ;;
#   shiro) export LAN=wlp3s0 ;;
# esac

export MONITOR=$(xrandr -q | grep primary | cut -d' ' -f1)
export MONITORS=( $(xrandr -q | grep ' connected' | cut -d' ' -f1) )
MONITOR=${MONITOR:-${MONITORS[0]}}

# Only have workspaces for primary monitor
for monitor in $MONITORS; do
  bspc monitor $monitor -d 0
done
bspc monitor $MONITOR -d {1,2,3,4,5}

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Rules
bspc rule -r '*'

bspc rule -a Pinentry state=floating center=on
bspc rule -a feh state=fullscreen
# bspc rule -a '*:scratch' state=floating sticky=on border=off rectangle=1000x460+480+1660
bspc rule -a '*:*:Zoom Meeting' state=floating

bspc rule -a firefox desktop='^3' follow=off
bspc rule -a 'Emacs:*' state=tiled desktop='^3' follow=off
bspc rule -a slack state=tiled desktop='^4' follow=off
bspc rule -a spotify state=tiled desktop='^4' follow=off
#
for file in $XDG_CONFIG_HOME/bspwm/rc.d/*; do
  source "$file"
done

bsp-layout set even
