#!/usr/bin/env bash

TIPS_STATUS=$(cat $HOME/.cache/eww/System-Menu/tips-lock)

echo "[eww] widget=system-menu launching widget"
if [[ $TIPS_STATUS == "on" ]]; then
    eww open-many --toggle background-closer system-menu tips
else
    eww open-many --toggle background-closer system-menu
fi
