{ colors, fonts, ... }:
''
TERM: screen-256color

font:
  # size: 16.0
  size : ${toString(fonts.mono.size)}
  normal:
    # family: JetBrains Mono
    family: ${fonts.mono.name}
    style: Medium

  Bold:
    # family: JetBrains Mono
    family: ${fonts.mono.name}
    style: Bold

  italic:
    # family: JetBrains Mono
    family: ${fonts.mono.name}
    style: Italic

window:
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
  dimensions:
    columns: 0
    lines: 0

  decorations: none

  dynamic_title: true

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 1

  padding:
    x: 30
    y: 30

  dynamic_padding: true

startup_mode: windowed

key: return,
mods: Command,
action: SpawnNewInstance

cursor:
  style: Block

use_thin_strokes: true

live_config_reload: true

# BEGIN ACE
colors:
  primary:
    background: '${colors.types.bg}'
    foreground: '${colors.types.fg}'
  cursor:
    text:       '${colors.black}'
    cursor:     '${colors.silver}'
  normal:
    black:      '${colors.black}'
    red:        '${colors.red}'
    green:      '${colors.green}'
    yellow:     '${colors.yellow}'
    blue:       '${colors.blue}'
    magenta:    '${colors.magenta}'
    cyan:       '${colors.cyan}'
    white:      '${colors.silver}'
  bright:
    black:      '${colors.black}'
    red:        '${colors.brightred}'
    green:      '${colors.brightgreen}'
    yellow:     '${colors.brightyellow}'
    blue:       '${colors.brightblue}'
    magenta:    '${colors.brightmagenta}'
    cyan:       '${colors.brightcyan}'
    white:      '${colors.white}'
# END ACE
''
