#!/usr/bin/env sh

bspc config borderless_monocle true
bspc config gapless_monocle    true
bspc config split_ratio        0.52

bspc config border_width 3
bspc config window_gap 20

bspc config normal_border_color "#ED8796"
bspc config active_border_color "#F5A97F"
bspc config focused_border_color "#F5A97F"
bspc config presel_feedback_color "#B7BDF8"

# Extra padding for polybar
bspc config top_padding 0
bspc config bottom_padding 0
bspc config -m primary top_padding 0
bspc config -m primary bottom_padding 50
