#!/usr/bin/env bash

STATE_DIR=$HOME/.cache/eww/System-Menu
STATE_FILE=$STATE_DIR/tips-lock

# Create the cache file with the current state if it doesn't already exist
if [[ ! -f $STATE_FILE ]]; then
    mkdir -p $STATE_DIR
    touch $STATE_FILE
    echo "on" > $STATE_FILE
fi

STATUS=$(cat $STATE_FILE)

toggle() {
    if [[ $STATUS == "on" ]]; then
        echo "off" > $STATE_FILE
        eww open --toggle tips
    else
        echo "on" > $STATE_FILE
        eww open --toggle tips
    fi
}

icon() {
    if [[ $STATUS == "on" ]]; then
        echo ""
    else
        echo ""
    fi
}

status() {
    if [[ $STATUS == "on" ]]; then
        echo "Tips on"
    else
        echo "Tips off"
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--icon" ]]; then
    icon
elif [[ $1 == "--status" ]]; then
    status
fi
