#!/usr/bin/env sh

bspc config borderless_monocle true
bspc config gapless_monocle    true
bspc config split_ratio        0.52

bspc config border_width 3
bspc config window_gap 20

bspc config normal_border_color "#ff777a"
bspc config active_border_color "#ffba95"
bspc config focused_border_color "#ffba95"
bspc config presel_feedback_color "#bd93f9"

# Extra padding for polybar
bspc config top_padding 0
bspc config bottom_padding 0
bspc config -m primary top_padding 55
bspc config -m primary bottom_padding 0
