#!/usr/bin/env bash

# Arguments:
# $1 the window number

# Toggles between the various desktop layouts for bspwm.
#
# The layouts are iterated through using the folowing order:
# 1 START: even
# 2:       tiled
# 3:       monocle
# 4:       grid
# 5 END:   wide
#
# When the end is reached it starts from the begging.

# Get the current layout
CURRENT=$(bsp-layout get $1)

# Tiled
if [[ $CURRENT == "even" ]]; then
    bsp-layout set tiled
fi

# Monocle
if [[ $CURRENT == "tiled" ]]; then
    bsp-layout set monocle
fi

# Grid
if [[ $CURRENT == "monocle" ]]; then
    bsp-layout set grid
fi

# Wide
if [[ $CURRENT == "grid" ]]; then
    bsp-layout set wide
fi

# Even
if [[ $CURRENT == "wide" ]]; then
    bsp-layout set even
fi
