# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ "${modulesPath}/installer/scan/not-detected.nix" ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelPackages = pkgs.unstable.linuxKernel.packages.linux_6_0;
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a1cc9a74-936e-4fb8-8a2f-33c8b695b695";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."nixos".device = "/dev/disk/by-uuid/e20a2125-314e-4be2-9d4d-295f842d70f5";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F699-5753";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/424cd402-5414-4cc1-affb-7b1cc9004350";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."home".device = "/dev/disk/by-uuid/a226bf61-0245-4694-9f38-5f83cdde0185";

  fileSystems."/media/procore" =
    { device = "/dev/disk/by-uuid/57e5d4fb-9024-4d1f-a0b8-985fcdecfc0c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."procore".device = "/dev/disk/by-uuid/0a44ca93-b8f7-43af-93ac-32037ec34956";

  fileSystems."/usr/vm/virtualbox" =
    { device = "/dev/disk/by-uuid/e41f49f8-e697-40c4-91d3-e4ec00d564f3";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."virtualbox".device = "/dev/disk/by-uuid/4923ab08-3587-48f3-b9aa-b2ebdd3a1fd1";

  fileSystems."/usr/vm/nixos" =
    { device = "/dev/disk/by-uuid/d4094193-d614-4286-b3c3-03a880f7d483";
      fsType = "ext4";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  networking.interfaces.eno0.useDHCP = lib.mkDefault true;
  networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  # CPU
  nix.settings.max-jobs = lib.mkDefault 20;
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Hardware
  modules = {
    hardware = {
      audio.enable = true;
      ergodox.enable = true;
      nvidia.enable = true;
      sensors.enable = true;
      system76.enable = true;
    };
  };

  # Displays
  services.autorandr = {
    enable = true;
    profiles = {
      workstation = {
        config = {
          "eDP-1-1" = {
            enable = true;
            mode = "1920x1080";
            primary = false;
            position = "0x1600";
            rate = "144.03";
            crtc = 4;
          };
          "HDMI-0" = {
            enable = true;
            # mode = "1920x1080";
            # primary = false;
            # position = "2690x0";
            mode = "3840x1600";
            primary = true;
            position = "1920x1080";
            rate = "60.00";
            crtc = 0;
          };
          "DP-1-1" = {
            enable = true;
            # mode = "3840x1600";
            # primary = true;
            # position = "1920x1080";
            mode = "1920x1080";
            primary = false;
            position = "2690x0";
            rate = "40.27";
            crtc = 5;
          };
        };
        fingerprint = {
          "eDP-1-1" = "00ffffffffffff0006af8f9700000000031e0104a526167803707593585a942920505400000001010101010101010101010101010101ce8f80b6703888403020a5007ed710000018ec3b80b6703888403020a5007ed710000018000000fd003c90b0b025010a202020202020000000fe004231373348414e30342e39200a007a";
          "HDMI-0" = "00ffffffffffff0010acf0a04c4d5430061c010380582578eeee95a3544c99260f5054a54b00714f81008180a940d1c0010101010101a36600a0f0401f6030203a00706f3100001a000000ff00393746385038323930544d4c0a000000fc0044454c4c20553338313844570a000000fd00185519731e000a202020202020012d02032af14d9005040302071601141f12135a230907078301000067030c001000383c0000000000000000023a801871382d40582c4500706f3100001e565e00a0a0a0295030203500706f3100001acd4600a0a0381f4030203a00706f3100001a134c00a0f040176030203a00706f3100001a00000000000000000000000000d8";
          "DP-1-1" = "00ffffffffffff001e6d0100010101010119010480a05a780aee91a3544c99260f5054a1080031404540614071408180010101010101023a801871382d40582c450040846300001e662150b051001b304070360040846300001e000000fd003a3e1e5310000a202020202020000000fc004b564d2048444d490a202020200172020338f154109f0413051403021220212215015d5e5f626364293d06c01507500957076e030c001000b83c20008001020304e50e60616566011d8018711c1620582c250040846300009e011d007251d01e206e28550040846300001e00000000000000000000000000000000000000000000000000000000000000000000001d";
        };
      };
      travel = {
        config = {
          "eDP-1-1" = {
            enable = true;
            mode = "1920x1080";
            primary = true;
            position = "0x0";
            rate = "144.03";
            crtc = 5;
          };
        };
        fingerprint = {
          "eDP-1-1" = "00ffffffffffff0006af8f9700000000031e0104a526167803707593585a942920505400000001010101010101010101010101010101ce8f80b6703888403020a5007ed710000018ec3b80b6703888403020a5007ed710000018000000fd003c90b0b025010a202020202020000000fe004231373348414e30342e39200a007a";
        };
      };
    };
  };
}
