# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  environment,
  ...
}: {
  imports = ["${modulesPath}/installer/scan/not-detected.nix"];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "sdhci_pci"];
  boot.initrd.kernelModules = ["nvidia"];
  boot.kernelModules = ["kvm-intel" "v4l2loopback"];
  boot.kernelPackages = pkgs.linuxKernel.packages.linux_6_12;
  boot.extraModulePackages = with config.boot.kernelPackages; [
    nvidia_x11
    v4l2loopback
  ];
  # See https://github.com/pop-os/gnome-shell/issues/124
  # Disabling psmouse to prevent the mouse moving when the laptop lid is closed
  # blacklist psmouse
  boot.extraModprobeConfig = ''
    options v4l2loopback devices=1 video_nr=1 card_label="OBS Cam" exclusive_caps=1
  '';

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a1cc9a74-936e-4fb8-8a2f-33c8b695b695";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."nixos".device = "/dev/disk/by-uuid/e20a2125-314e-4be2-9d4d-295f842d70f5";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F699-5753";
    fsType = "vfat";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/424cd402-5414-4cc1-affb-7b1cc9004350";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."home".device = "/dev/disk/by-uuid/a226bf61-0245-4694-9f38-5f83cdde0185";

  fileSystems."/media/procore" = {
    device = "/dev/disk/by-uuid/57e5d4fb-9024-4d1f-a0b8-985fcdecfc0c";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."procore".device = "/dev/disk/by-uuid/0a44ca93-b8f7-43af-93ac-32037ec34956";

  fileSystems."/usr/vm/virtualbox" = {
    device = "/dev/disk/by-uuid/e41f49f8-e697-40c4-91d3-e4ec00d564f3";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."virtualbox".device = "/dev/disk/by-uuid/4923ab08-3587-48f3-b9aa-b2ebdd3a1fd1";

  fileSystems."/usr/vm/nixos" = {
    device = "/dev/disk/by-uuid/d4094193-d614-4286-b3c3-03a880f7d483";
    fsType = "ext4";
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  networking.interfaces.eno0.useDHCP = lib.mkDefault true;
  networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  # CPU
  nix.settings.max-jobs = lib.mkDefault 20;
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Hardware
  modules = {
    hardware = {
      audio.enable = true;
      ergodox.enable = true;
      nvidia.enable = true;
      sensors.enable = true;
      system76.enable = true;
    };
  };
}
